[project]
name = "blog"
version = "0.1.0"
description = "Blog Static Website Generator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown",
    "pyyaml",
    "jinja2",
    "feedgen",
    "Pillow"
]
